package pkg

import (
	"io/ioutil"
	"strings"
)

func (s *NetCardInfo) readDNS() error {
	byt, err := ioutil.ReadFile("/etc/resolv.conf")
	if err != nil {
		return err
	}
	// # Generated by NetworkManager
	// nameserver 192.168.0.186

	arLine := strings.Split(string(byt), "\n")

	for _, line := range arLine {
		arKv := strings.Split(line, " ")
		if len(arKv) == 2 {
			k := TrimStr(arKv[0])
			v := TrimStr(arKv[1])
			if k == "nameserver" {
				if s.DNS1 == "" {
					s.DNS1 = v
				} else {
					s.DNS2 = v
				}

			}
		}
	}
	return nil
}
